### ISSUE TITLE
Adding a new voice to the UI

### ISSUE THREAD

**Issue by ElhamAhmedian** [KoeAI/LLVC#3]
Hello,
If I train my own voice, How do I add it to your beautiful UI? 

Thanks!!!

**Comment by ksadov** [comment]
Currently, the Windows UI provided at https://koe.ai/recast/download/ is only compatible with the Desktop App Voices listed here, which are downloaded from the Koe AI servers: https://koe.ai/recast/samples/

**Comment by ksadov** [comment]
There currently aren't any plans to make the UI compatible with local LLVC models, but maybe that'll change in the future, we'll see.

**Comment by ElhamAhmedian** [comment]
Let me understand-the Desktop App models are not the same as the ones trained using this repo? 
So if I train and run in real-time without the Desktop UI, it will not sound the same? 
Thanks!

**Comment by ksadov** [comment]
The Desktop App voices are trained on proprietary data. However, if you were to gather a similar-sounding dataset and trained on that using code from this repository, the resulting voice should match the quality of the Desktop App voices.

**Comment by ElhamAhmedian** [comment]
Thanks, and how do I run my trained model in real-time without the UI?
