### ISSUE TITLE
How do you run inference from a mic in real time? 

### ISSUE THREAD

**Issue by ElhamAhmedian** [KoeAI/LLVC#5]
Thanks

**Comment by ElhamAhmedian** [comment]
Anyone?

**Comment by ksadov** [comment]
https://github.com/w-okada/voice-changer will soon support LLVC inference. If you have a Window's machine, you can also download the [Koe AI desktop app](https://koe.ai/recast/download/) and run inference on pretrained models provided by Koe AI.
